# Generated by Django 5.0.4 on 2024-04-12 07:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="amazon.basemodel",
                    ),
                ),
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("address", models.TextField()),
            ],
            bases=("amazon.basemodel",),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="amazon.basemodel",
                    ),
                ),
                (
                    "order_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("item", models.CharField(max_length=50)),
                (
                    "customer_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="amazon.customer",
                    ),
                ),
            ],
            bases=("amazon.basemodel",),
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="amazon.basemodel",
                    ),
                ),
                (
                    "dispute_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dispute_reason", models.TextField()),
                (
                    "status_tracking",
                    models.IntegerField(
                        choices=[
                            (1, "RAISED"),
                            (2, "ACTIVE"),
                            (3, "INACTIVE"),
                            (4, "CLOSED"),
                            (5, "DUPLICATE"),
                        ],
                        default=1,
                    ),
                ),
                ("resolution", models.TextField(max_length=100)),
                (
                    "original_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="amazon.order"
                    ),
                ),
            ],
            bases=("amazon.basemodel",),
        ),
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="amazon.basemodel",
                    ),
                ),
                (
                    "return_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("return_reason", models.TextField()),
                (
                    "return_tracking",
                    models.IntegerField(
                        choices=[(1, "INITIATED"), (2, "IN PROGRESS"), (3, "RETURNED")],
                        default=1,
                    ),
                ),
                (
                    "original_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="amazon.order"
                    ),
                ),
            ],
            bases=("amazon.basemodel",),
        ),
    ]
